### PR TITLE
Fixed some more warnings

### PR DESCRIPTION
**Pull request by likp**
Fixed the warnings that was left in Visual Studio.

### CODE REVIEW

**Review by JohannesFinsveen — APPROVED** [review]
Very good :-)

**Comment by likp** [comment]
@JohannesFinsveen can you look at why the test are failing in this PR

**Comment by JohannesFinsveen** [comment]
> @JohannesFinsveen can you look at why the test are failing in this PR

Did you recreate the menu? @likp

**Comment by likp** [comment]
> > @JohannesFinsveen can you look at why the test are failing in this PR
> 
> Did you recreate the menu? @likp

Yes, I did. I guess I should not have added that change?

**Comment by JohannesFinsveen** [comment]
> > > @JohannesFinsveen can you look at why the test are failing in this PR
> > 
> > 
> > Did you recreate the menu? @likp
> 
> Yes, I did. I guess I should not have added that change?

We need to fix than, but perhape in a  different issue?

**Pull request merged**
