### PR TITLE
58 try global usings

### PR DESCRIPTION
**Pull request by JohannesFinsveen**

### CODE REVIEW

**Comment by JohannesFinsveen** [comment]
I think the PxWeb folder is too wide, in a topic sense,  for Global using to be usefull. But I think it makes sence for the others.  Not sure what to do with implisitt usings, the bigger the folder, the more sence it makes. Lets talk ...

**Comment by JohannesFinsveen** [comment]
This is branch from #54 , only the last 3(now) commits belong to #58

**Comment by likp** [comment]
> I think the PxWeb folder is too wide, in a topic sense, for Global using to be usefull. But I think it makes sence for the others. Not sure what to do with implisitt usings, the bigger the folder, the more sence it makes. Lets talk ...

Maybe we should not put everting into the global usings but only have what is common to every file.

**Comment by JohannesFinsveen** [comment]
@likp I made a small one :-) We could perhaps make an issue on making some common code cleanup profile or something to that effect ..

**Review by likp — APPROVED** [review]

**Pull request merged**
