### PR TITLE
Adding CORS header on preflight request

### PR DESCRIPTION
**Pull request by likp**
Added a middleware to handle options request

### CODE REVIEW

**Review by MikaelNordberg — APPROVED** [review]
Looks good

**Comment by runejo** [comment]
Hi! 
I have tried to verify this, but i can't trigger the new code. Could you the post the curl example?
This is what i tried
```
curl -I -X OPTIONS -H "Origin: http://localhost:3000" "http://localhost:43071/api/v2/tables/TAB004/data?outputFormat=json-stat2"

HTTP/1.1 405 Method Not Allowed
Date: Fri, 08 Mar 2024 15:31:06 GMT
Server: Kestrel
Access-Control-Allow-Origin: *
Allow: GET, POST
Transfer-Encoding: chunked
```

I'm also starting to wonder if we where testing it the wrong way. Looking at the browser requests it should be more like this
```
curl -I -X OPTIONS -H "Origin: http://localhost:3000" -H 'Access-Control-Request-Method: POST' -H "Access-Control-Allow-Headers: Content-Type" "http://localhost:43071/api/v2/tables/TAB004/data?outputFormat=json-stat2"

HTTP/1.1 204 No Content
Date: Fri, 08 Mar 2024 15:38:23 GMT
Server: Kestrel
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: GET,POST
Access-Control-Allow-Origin: *
```
This already works on the main branch, but I had to add these two lines 
```
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: GET,POST
```

To remove this error I saw in Chrome when testing agains our deployed version

> Access to fetch at 'https://pxapi2.staging-bip-app.ssb.no/api/v2/tables/TAB004/data?outputFormat=json-stat2' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by likp** [comment]
@runejo good catch! The middleware worked fine in my test project but it did not i the PxWebApi 2.0 project instead it throw an exception. I have written a fix for it and now the curl query above should work.

**Comment by runejo** [comment]
Yes now it works 👍 

```
curl -I -X OPTIONS -H "Origin: http://localhost:3000" "https://localhost:5001/api/v2/tables/TAB004/data?outputFormat=json-stat2"

HTTP/1.1 200 OK
Date: Mon, 11 Mar 2024 15:16:30 GMT
Server: Kestrel
Access-Control-Allow-Origin: *
Allow: GET, POST, OPTIONS
Transfer-Encoding: chunked
```

**Review by runejo — APPROVED** [review]

**Pull request merged**
